xima_depmon_index:
    path: "/"
    defaults: { _controller: "xima_depmon.default:index", _format: html }

xima_depmon_detail:
    path: "/detail/{project}"
    defaults: { _controller: "xima_depmon.default:detail", _format: html }

xima_depmon_state:
    path: "/state/{project}"
    defaults: { _controller: "xima_depmon.default:state", _format: html }

xima_depmon_update:
    path: "/update"
    defaults: { _controller: "xima_depmon.default:update", _format: html }