version: '2'

services:
  apache:
    image: httpd:2.4.23-alpine
    links:
      - phpfpm
    volumes:
      - ../source/:/usr/local/apache2/htdocs/:cached
      - ./srv-conf/httpd.conf:/usr/local/apache2/conf/httpd.conf:cached

  phpfpm:
    build:
      context: .
      dockerfile: dockerfiles/php
    user: "1000:33"
    volumes:
      - ../source/:/usr/local/apache2/htdocs/:cached
      - ./srv-conf/php.ini:/usr/local/etc/php/conf.d/zz-php.ini:ro
      - ./srv-conf/xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini:ro
      - ./srv-conf/composer/auth.json:/.composer/auth.json:ro
    working_dir: /usr/local/apache2/htdocs/
